version: '2'
services:
  kafka:
    image: spotify/kafka:${TAG_KAFKA}
    ports:
      - 2181:2181
      - 9092:9092
  registry-server:
    image: ${REPO}/ssg/registry-server:${TAG_REGISTRY_SERVER}
    ports:
      - 8761:8761
  config-server:
    image: ${REPO}/ssg/config-server:${TAG_CONFIG_SERVER}
    ports:
      - 8888:8888
    links:
      - kafka
      - registry-server
  auth-service:
    image: ${REPO}/ssg/auth-service:${TAG_AUTH_SERVICE}
    ports:
      - 9081:9081
    links:
      - kafka
      - registry-server
      - config-server
  sopridees-service:
      image: ${REPO}/ssg/sopridees-service:${TAG_SOPRIDEES_SERVICE}
      ports:
        - 8280:8280
      links:
        - kafka
        - registry-server
        - config-server
  user-service:
      image: ${REPO}/ssg/user-service:${TAG_USER_SERVICE}
      ports:
        - 8380:8380
      links:
        - kafka
        - registry-server
        - config-server
  proxy-server:
    image: ${REPO}/ssg/proxy-server:${TAG_PROXY_SERVER}
    ports:
      - 9080:9080
    links:
      - kafka
      - registry-server
      - config-server
  dashboard-hystrix:
    image: ${REPO}/ssg/dashboard-hystrix:${TAG_DASHBOARD_HYSTRIX}
    ports:
      - 6161:6161
      - 8989:8989
    links:
      - kafka
      - registry-server
      - config-server
  dashboard-zipkin:
    image: ${REPO}/ssg/dashboard-zipkin:${TAG_DASHBOARD_ZIPKIN}
    ports:
      - 6262:6262
    links:
      - kafka
      - registry-server
      - config-server
