spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SopraSteriaGroup/initiatives_properties
          username: initiativesproject
          password: initiativespass123
server:
  port: ${config.uri:8888}
eureka:
  instance:
    hostname: localhost
  client:
    trust-store: classpath:truststore.jks
    trust-store-password: changeit
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: https://localhost:8761/eureka/
management:
  security:
    enabled: false

---

spring:
  profiles: docker
  cloud:
    stream:
      kafka:
        binder:
          zkNodes: kafka
          brokers: kafka
eureka:
  instance:
    hostname: config-server
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://registry-server:8761/eureka/